import type { Metadata } from "next";
import ClientSnackbarProvider from "@/context/SnackbarProvider";
import AppTheme from "@/theme/AppTheme";
import Sidebar from "@/components/Sidebar";
import "./global.css";
import { Box } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppTheme>
          <ClientSnackbarProvider>
            <Box sx={{ display: "flex" }}>
              <Sidebar />
              {children}
            </Box>
          </ClientSnackbarProvider>
        </AppTheme>
      </body>
    </html>
  );
}
